config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/consejos_para_todos' => 'pages#consejos_para_todos'
  
  get 'pages/cuando_no' => 'pages#cuando_no'
  
  get 'pages/alimentos_peligrosos' => 'pages#alimentos_peligrosos'

  get 'pages/about' => 'pages#about'

  get 'pages/que'

  get 'pages/definicion' => 'pages#definicion'

  get 'pages/beneficios' => 'pages#beneficios'

  get 'pages/botella'

  get 'pages/guia_para_empezar' => 'pages#guia_para_empezar'

  get 'pages/edad' => 'pages#edad'

  get 'pages/tipo' => 'pages#tipo'

  get 'pages/seguridad' => 'pages#seguridad'

  get '/pages/ahogamiento' => 'pages#ahogamiento'

  get '/pages/primeros_auxilios' => 'pages#primeros_auxilios' 

  get '/pages/nutricion' => 'pages#nutricion'

  get '/pages/hierro' => 'pages#hierro'

  get '/pages/cantidades' => 'pages#cantidades'

  get '/pages/alergias' => 'pages#alergias'
  
  get '/pages/contacto' => 'pages#contacto'
  
  get '/pages/libros' => 'pages#libros'
  
  get '/pages/tienda' => 'pages#tienda'
  
  get '/pages/estudios_y_referencias' => 'pages#estudios_y_referencias'
  
  get '/pages/reflejo_nauseoso' => 'pages#reflejo_nauseoso'
  
  get '/pages/reflejo_extrusion' => 'pages#reflejo_extrusion'
  
  root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def que
  end

  def definicion
  end

  def porque
  end

  def botella
  end

  def guia_para_empezar
  end

  def edad
  end

  def tipo
  end

  def seguridad
  end

  def ahogamiento
  end

  def primeros_auxilios
  end

  def nutricion
  end

  def hierro
  end

  def cantidades
  end

  def alergias
  end
  
  def libros
  end
  
  def tienda
  end
  
  def contacto
  end
  
  def alimentos_peligrosos
  end
  
  def cuando_no
  end 
  
  def consejos_para_todos
  end 
  
  def estudios_y_referencias
  end
  
  def reflejo_nauseoso
  end
  
  def reflejo_extrusion
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/pages/cuando_no.html.erb
<div class="container">
    <div style="background:transparent !important" class="jumbotron vertical-center">
        <div class="container content">
            <h1 class="entry-title">Cuando no se recomienda Baby Led Weaning</h1>
            <p>
                Baby led weaning no es para todos:
            </p>
            <ul>
                <li>
                    <p>
                        Si tu bebé fue prematuro (menos de 37 semanas de gestación)
                    </p>
                </li>
                <li>
                    <p>
                        Si tu bebé presenta retrasos de desarrollo
                    </p>
                </li>
                <li>
                    <p>
                        Si tu bebé tiene problemas de deglución (tragar) o comer
                    </p>
                </li>
            </ul>
            <br/>
            <p>
                A estos bebés no es recomendado empezar con baby led weaning o auto alimentación.
            </p>
            <br/>
            <p>
                Si tu bebé no muestra interés por la comida o no ves que tu bebé coma más cantidad semana tras semana debes tratar otra técnica. Puedes volver a tratar mas adelante.
            </p>
            <br/>
            <p>
                Existen muchos
                <%=link_to "conceptos benéficos de baby led weaning", pages_consejos_para_todos_path%> o auto alimentación que puedes incorporar en la introducción a sólidos sin adoptar la técnica:
            </p>
            <ul>
                <li>
                    <p>
                        Saber cuando tu
                        <%=link_to "bebé está físicamente listo", pages_edad_path%>,
                    </p>
                </li>
                <li>
                    <p>
                        Bebé acompañe a la familia a la hora de la comida,
                    </p>
                </li>
                <li>
                    <p>
                        Reconocer y respetar sus señales de saciedad (sobre todo si tu bebé toma formula),
                    </p>
                </li>
                <li>
                    <p>
                        Ofrecerle una variedad de especias para condimentar su comida y más,
                    </p>
                </li>
                <li>
                    <p>
                        Que tu bebé asocie la comida con algo positivo y sea una experiencia placentera entre otros.
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/pages/definicion.html.erb
<div class="container">
    <div style="background:transparent !important" class="jumbotron vertical-center">
        <div class="container content">
            <h1 class="entry-title">¿Qué es el baby-led weaning?</h1>
            <p>
                <b class="onceUpon">De manera muy resumida,</b> es una manera de comenzar la introducción de sólidos sin purés ni papillas. Por sólidos se entiende cualquier otra cosa diferente a la leche materna o fórmula, ya que durante los primeros
                6 meses la dieta del bebé debe ser única y exclusivamente leche. Ojo, los sólidos <em>complementan</em> la leche, no son la fuente de nutrición principal.
            </p>
            <br/>
            <p>
                <%=link_to "Alrededor de los 6 meses", pages_edad_path%>, el sistema digestivo del bebé comienza a madurar y a estar listo para algo diferente a la leche materna (o fórmula). Es entonces que tienes la opción de introducir a tu bebé el maravilloso mundo de la comida.
            </p>
            <br/>
            <p>
                Para ello existen muchas técnicas. Y aunque comenzar a darle cucharaditas de purés y papillas sigue siendo la más conocida, existen otras. Eso es lo que es la auto alimentación: una manera de introducir sólidos en la cual tu bebé sea quien mande. De ahí
                el término en inglés “baby-led”, oseáse dirigido por el bebe y “weaning”, en el sentido británico que quiere decir <em>complementar</em> la alimentación del bebé con sólidos.
            </p>
            <br/>
            <p>
                Con baby led weaning o auto alimentación puedes ofrecerle a tu bebé comida apropiada para su edad, cortada o ligeramente machacada, que él mismo agarre (o aplaste) y meta a su boca (eventualmente). Tu le proporcionas la comida, él decide cómo y cuánto
                comer. Es importante que respetes su ritmo y dejes que sea él quien controle lo que meta a su boca, <em><b>tú 
            nunca debes de introducirle algo a la boca!</b></em>
            </p>
            <br/>
            <blockquote>
                <p class="quoteContent">
                    <b class="quotes">"</b>El objetivo de la alimentación infantil no es nutricional...es educacional. Le damos otros alimentos porque tiene que ir aprendiendo a comer normal.<b class="quotes">"</b> </p>
                <footer>Dr. Carlos González, pediatra y escritor</footer>
            </blockquote>
            <br/>
            <p>
                Baby led weaning o auto alimentación es una manera natural y divertida de comenzar una nueva etapa. Tiene muchos
                <%=link_to "beneficios", pages_beneficios_path%> pero se debe saber de qué manera
                    <%=link_to "hacerlo correctamente", pages_guia_para_empezar_path%>. Te recomiendo que leas ampliamente acerca de este método y decidas si es adecuado para tu familia. Además de este sitio, incluyo un enlace a algunos libros entre ellos el de Gill Rapley, quien es quien acuñó el término “baby led
                        weaning” y la autora del libro de referencia, el de Carlos González, otra referencia en España.</p>
            <br/>
            <p>
                Puedes decidir mezclar baby led weaning o autoalimentación con ocasionales purés y papillas. Esto también se vale, no es todo o nada. El chiste es que funcione para ti y tu familia. Y aún si decides comenzar, o continuar, alimentando a tu hijo de otra
                manera te recomiendo echar un ojo a
                <%=link_to "esta sección", pages_consejos_para_todos_path%>.
            </p>
        </div>
    </div>
</div>

app/views/pages/edad.html.erb
<div class="container">
    <div style="background:transparent !important" class="jumbotron vertical-center">
        <div class="container content">
            <h1 class="entry-title">¿Cuándo comenzar BLW? </h1>
            <p>
                <b class="onceUpon">Los expertos recomiendan una dieta exclusiva de leche materna</b> hasta los 6 meses de edad y hasta los 2 años en complemento a los sólidos. Es entre los 6 y 7 meses de edad que el aparato digestivo de tu bebé está
                lo suficientemente maduro para comenzar a complementar su alimentación con sólidos. Sin importar de qué manera lo vas a hacer, espérate hasta que tenga al menos 6 meses y aún mejor hasta que cumpla con los requisitos que se enlistan abajo:
            </p>
            <br/>
            <p>
                Cuándo comenzar con sólidos depende de tu bebé. El será quien te indique si está físicamente desarrollado y listo. Recuerda que cada niño es diferente y se desarrolla a su propio paso. Reitero que esta lista<em> debería aplicarse para cualquier manera de
            comenzar con sólidos</em> pero es <b>IMPERATIVA si practicas baby led weaning</b> o auto alimentación. En este caso, tu bebé tiene que cumplir con <u>todos los requisitos antes de comenzar</u>. Aquí las indicaciones de que pueden empezar:
            </p>
            <br/>
            <h2>Esperáte hasta los 6 meses</h2>
            <p>
                Tu bebé tiene al menos 6 meses, no hay ninguna urgencia por comenzar, la leche materna lo abasta con todo lo que necesita entonces no te preocupes si tu bebé no parece estar listo hasta los 7 meses. No hay nada mágico que sucede a los 6 meses pero suele
                ser que es en este momento cuando muchos bebés cumplen con estos requisitos. En cambio es raro que esto suceda antes de este tiempo.
            </p>
            <br/>
            <h2>Tu bebé se sienta derecho (con o sin ayudaa)</h2>
            <p>
                Tu bebé mantiene la cabeza perfectamente levantada, es capaz de sentarse cómodamente en una sillita alta o silla de bebé y mantener perfecto control de su cabeza. No quiere decir que se pueda sentar solo sin apoyo pero sí debe de poderse sentar derecho
                en una silla. ¿Porqué? Porque a la hora de comer, la cabeza, garganta y estómago de tu bebé deben estar perfectamente alineados para asegurar que nada se le 'vaya chueco'.
            </p>
            <br/>
            <h2>Desaprición del reflejo de extrusión</h2>
            <p>
                Tu bebé ya no tiene el
                <%=link_to "reflejo de extrusión", pages_reflejo_extrusion_path%>, el movimiento que hace tu bebé con su lengua para expulsar <b>cualquier no-líquido</b> de su boca. Este reflejo cuida a tu bebé ya que se expulsa al exterior cualquier cosa otra que la leche. Es su manera de decirnos que todavía no estan
                    listos para ningun otro alimento.
            </p>
            <br/>
            <h2>Muestra interés a la hora de la comida</h2>
            <p>
                Tu bebé muestra interés cuando comes, está interesado en lo que haces a la hora de comer y sobre lo que hay en tu plato. Tal vez trate de robarte un pedazo de lo que estés comiendo.
            </p>
            <br/>
            <h2>Desarrollo motor grueso</h2>
            <p>
                Tu bebé es capaz de agarrar objetos y llevárselos a la boca, aunque todavía no domine el agarre de pinza (tomar objetos entre el pulgar y el índice). Este normalmente es adquirido a partir del 8avo mes y es importante para atrapar objetos pequeños como
                chícharos. Al principio tal vez no coma nada pero por el momento, la introducción de sólidos es educacional, no nutricional.
            </p>
            <br/>
            <h2>No se trata de nutrición</h2>
            <p>
                No olvides que baby led weaning es lento y requiere de paciencia sobre todo al principio. Pero la introducción de sólidos no debe ser nutricional sino educativa: tu bebé practica su motricidad gruesa y óculo-manual (agarra un objeto y se lo lleva a la
                boca), descubre texturas y sabores, aprende a convivir en la mesa, aprende a tomar decisiones (le gusta o no lo que probó) y muchos
                <%=link_to "otros beneficios", pages_beneficios_path%> más. Si quiere saber cuánto debería estar comiendo lee
                    <%=link_to "'Cantidades'", pages_cantidades_path%> en la sección de
                        <%=link_to "'Nutrición'", pages_nutricion_path%>.
            </p>
            </br>
            <p>
                Para comenzar con baby led weaning o autoalimentación, tu bebe tiene que cumplir con <u>todos los requisitos</u>. Si le falta alguno todavía no está físicamente listo y <b>no debes de intentarlo </b>ya que lo podrías poner en peligro.
                Tu bebé estará listo a su ritmo y cuando lo esté podrás comenzar baby led weaning o auto alimentación.
            </p>
            </br>
            <p>
                Hasta entonces ten paciencia y continúa dándole sus tomas de leche. No te preocupes por los nutrientes, la leche materna tiene todo lo que necesita. Consulta con tu pediatra antes de empezar para saber si este método es adecuado para ti y tu bebé. No
                hay ninguna razón por la cual no lo sea
                <%=link_to "al menos", pages_cuando_no_path%> de que tu bebe tenga algun impedimento físico o un retraso en el desarrollo, haya nacido prematuro (menos de 37 semanas de gestación) o tenga problemas para deglutir o comer.
            </p>
        </div>
    </div>
</div>

app/views/pages/estudios_y_referencias.html.erb
<div class="container">
    <div style="background:transparent !important" class="jumbotron vertical-center">
        <div class="container content">
            
        </div>
    </div>
</div>

app/views/pages/guia_para_empezar.html.erb
<div class="container">
    <div style="background:transparent !important" class="jumbotron vertical-center">
        <div class="container content">
            <h1 class="entry-title">Tu guía de BLW</h1>
            <div>
                <img src="https://lh3.googleusercontent.com/-pYC6eKkDi0k/Vup4D_LPUFI/AAAAAAAAAHc/5Y3LvalrrlYeiWBsyFqkuBVUe-n_mjPXwCCo/s851-Ic42/Guia%2Bempezar%2Bpage.png" class="img-fluid img-responsive" alt="Responsive image">
            </div>
            </br>
            <p><b class="onceUpon">¡Por fin tu bebé cumple con <%= link_to "todos los requisitos", pages_edad_path%> para empezar sólidos!</b> Es un momento muy emocionante porque empieza una etapa muy divertida. Si ya te decidiste empezar con baby led weaning
                o auto alimentación abajo está una guía que te ayudará a saber ¿por dónde empezar?, ¿qué puedes esperar? y ¿qué vas a necesitar?</p>
            <h3 class="entry-content">La silla</h3>
            <p>
                Para empezar BLW es necesario tener una sillita donde el bebé pueda sentarse cómodamente y estar siempre derecho. Esto es primordial para su seguridad: su cabeza y espalda deben de estar siempre derechas y alineadas. BLW implica batidero. Todo va a acabar
                batido: bebé, silla, piso y si las cortinas están cerca también. Por eso entre más ‘básica’ sea la silla, mejor. Esas sillitas preciosas con asientos de tela van a volverse tu pesadilla. El asiento de tela lo tendrás que lavar después
                de cada comida. Lo más fácil y práctico es una silla de plástico con charola. Algo facil de lavar, incluso que podrías meter a la regadera o limpiar a manguerazos (créeme que a veces es lo más fácil!) es lo mejor.
            </p>
            <h3 class="entry-content">Tipo de comida</h3>
            <p>
                Vas a necesitar comida. Olvídate de la ‘comida de bebé’, comida es comida. Mientras no tenga sal ni aditivos, le puedes dar una
                <%=link_to "gran variedad de alimentos", pages_tipo_path%>. Para asegurar que no tenga ni sal ni aditivos es mejor prepararla tú. Los bebés tienen un paladar inquisitivo y les gusta la comida con sabor, igual que a nosotros. Usa hierbas y especias. Zanahoria cocida con un poquito de ajo y cilantro
                    (muy bien lavado y desinfectado), una rebanada de manzana bien cocida con canela y jengibre o un pedazo de pollo con curry. Trata de privilegiar comida
                    <%=link_to "alta en hierro", pages_hierro_path%> y con un contenido alto de energia
            </p>
            <h3 class="entry-content">Cantidades</h3>
            <p>
                Ofrécele medio plátano, dos o tres tiritas de zanahoria o tres espaguetis. Tu bebé descubre todo por primera vez, no lo abrumes con mucha comida ni mucha variedad. Al principio deja que comprenda de qué se trata y desarrolle su habilidad de llevarse comida
                a la boca. Después sí debes de ofrecer
                <%=link_to "una alimentación variada", pages_tipo_path%> pero al principio una o dos cosas es más que suficiente. Empieza con una comida al día y trata de incrementar una comida gradualmente hasta llegar a 5 comidas (3 comidas y 2 snacks) a los 12 meses. Recuerda que esto es una guía, cada bebé
                    es diferente, pueden tardar más o menos. Si te preocupa que tu bebé no está comiendo lo suficiente, écha un ojo
                    <%=link_to "'Cantidades'", pages_cantidades_path%> en la sección de
                        <%=link_to "'Nutrición'", pages_nutricion_path%>
                            para darte una idea de lo que se recomienda comer a cada edad. Y no olvides que hasta los 12 meses la leche sigue siendo su fuente principal de nutrición.
            </p>
            <h3 class="entry-content">El tamaño</h3>
            <p>
                El tamaño importa. Piensa en una papa a la francesa como el largo ideal. El chiste es que tu bebé pueda agarrarlo fácilmente, sobre todo si todavía no domina el agarre de pinza (tomar objetos entre el pulgar y el índice) que normalmente aparace alrededor
                del 8avo mes. Si el pedazo es muy pequeño, tu bebé no podrá recogerlo y llevárselo a la boca. Debe ser lo suficientemente largo para poder agarrarlo con el puño y que le sobre una buena parte para llevarlo a la boca. De otro modo tendrá
                que abrir su puño para meterse el pedazo a la boca y esto puede resultar muy complicado y frustrante.
            </p>
            <h3 class="entry-content">Textura</h3>
            <p>
                La textura ideal es aquella que puedas deshacer fácilmente cuando la aplastas entre tu pulgar e índice. La fruta como el plátano, la fresa, el mango y el aguacate se le pueden dar crudos. La manzana por ejemplo debes cocerla al vapor, horno o como prefieras
                hasta que consiga una textura suave. Puedes agregarle canela o un poco de jengibre si gustas. A los bebés les encantan las especias, ¡ya veras!
            </p>
            <h3 class="entry-content">La hora</h3>
            <p>
                Es importante elegir en qué momento del día comienzas a darle de comer. Como al principio no comen mucho (o nada), es mejor que a tu bebé lo sientes a ‘comer’ justo después de haber tomado su leche y su siesta. Un bebé que tiene hambre o está cansando
                va a estar molesto y no tendrá ni el humor ni la paciencia para explorar lo que le pongas enfrente. También es importante que el bebé coma acompañado. Si puedes, trata de sentar al bebé a la hora de comer y dale lo mismo que comas tu,
                <%=link_to "si es apropiado", pages_tipo_path%>. Los bebés aprenden por imitación: quieren hacer todo lo que nosotros hacemos. Entonces incorporarlo a la hora de la comida familiar es un excelente momento! En caso de que esto no sea posible, siéntate a comer al menos una botana o lo
                    que coma tu bebé y disfruten de un momento juntos.
            </p>
            <h3 class="entry-content">Frecuencia</h3>
            <p>
                Al principio puedes hacerlo una vez al día, recordando que no estás sustituyendo ninguna comida. El bebé continúa con sus tomas de leche normales solamente que ahora tienen una nueva actividad. Progresivamente y como vaya mejorando su habilidad, podrás
                aumentar la frecuencia a dos o tres veces al día. Es por eso que a la hora de escoger qué alimentos dar, elije comida
                <%=link_to "alta en hierro", pages_hierro_path%> y de alto contenido energético. Trata de
                    <%=link_to "aumentar una comida cada mes", pages_cantidades_path%> para estar en 3 comidas al final del 8avo mes y 3 comidas y 2 colaciones a los 12 meses.
            </p>
            <h3 class="entry-content">Señales de saciedad</h3>
            <p>
                Cuando tu bebé comience a tirar repetitivamente las comida, se distraiga con otras cosas, te estire los brazitos o empieza a mostrarse inquieto, todas estas son muestras que ya termino. Es importante seguir respetando las señales de saciedad de tu bebé
                ya que si los ignoras puedes sobrealimentarlos y esto aumenta el riesgo de sobrepeso además de causar enojo y frustracion. Recuerda que uno de los conceptos más importantes de BLW es crear experiencias positivas con la hora de comer para
                fomentar una relacion positiva entre tu bebé y la comida.

                <p>
                    Si tu bebé ha sido amamantado es probable que conozcas los signos de saciedad. Si le has dado botella (fórmula o leche materna) puedes leer la sección de
                    <%=link_to "'Bebés de botella'", pages_botella_path%> para familiarizarte en caso de que no los conozcas. Es muy importante reconocerlos sobre todo ahora que comienza sólidos porque progresivamente tomará menos leche y debes ajustar las cantidades de acuerdo a las necesidades de tu bebé.
                </p>

            </p>
            <h3 class="entry-content">Platos y cucharas</h3>
            <p>
                ¿Para que? Lo puedes intentar si quieres pero para lo único que sirven los platos en este momento son para tirar o golpear y hacer ruido. Ofrecele la comida en la charola de su sillita.
            </p>
            <h3 class="entry-content">Una actividad</h3>
            <p>
                Sobre todo al principio, piensa en la hora de la comida como una actividad más en la rutina de tu bebé. La hora del baño es para lavarse, la hora de la siesta es para dormir y la hora de la comida (al menos por ahora) es la hora para divertirse y descubrir
                colores, texturas y uno que otro sabor. Porque al principio tu bebé tal vez no se lleve nada a la boca, entonces es mejor que pienses en esto como una actividad divertida. El chiste es que tu bebé comience a tener una excelente relación
                con la comida, una relación sana que le dure para toda su vida. Si te enojas o desesperas tu bebé no querrá repetirlo. Las primeras semanas o meses, tu bebé lograra comer
                <%=link_to "realmente muy poco ", pages_cantidades_path%>, pero descubrirá un mundo extraordinario de texturas, colores, olores y sabores. Va a anticipar el momento de sentarse en su sillita y esto comenzará una buena relación entre tu bebé y la comida. Poco a poco, irá comiendo más y más hasta
                    ser un campeón comelón! Y mejor aún, no habrá lugar en tu casa para las batallas a la hora de comer.
            </p>
        </div>
    </div>
</div>

app/views/pages/libros.html.erb
<div class="container">
    <div class="jumbotron-narrow">
        <div class="container content">
            <h1 class="entry-title">¿Qué es el baby-led weaning?</h1>

        </div>
    </div>
</div>

app/views/pages/nutricion.html.erb
<div class="container">
    <div style="background:transparent !important" class="jumbotron vertical-center">
        <div class="container content">
                        <h1 class="entry-title">Nutrición</h1>

            <p>
                <b class="onceUpon">Hasta al menos los 6 meses de edad,</b> la dieta 
                de tu bebé debe ser 100% exclusivamente leche materna o fórmula. Y esta 
                dieta cumple con todos los requerimientos nutritivos de tu bebé hasta 
                ese momento. Alrededor de los 6 meses, puede ser un poco antes o después, 
                tu bebé te indicará que esta listo para comenzar con sólidos. Recuerda que 
                cada bebé es único y diferente y hasta no cumplir con todos <%= link_to "los requisitos", pages_edad_path%>, 
                no debemos introducir sólidos.
            </p>
            <br/>
            <p>
                Por sólidos, se entiende <b>cualquier cosa otra</b> que la leche. Y la introducción de 
                éstos únicamente <em><u>complementan </u></em>la dieta de tu bebé. Sobre todo durante los primeros 
                meses, <b>las tomas de leche deben continuar idénticas y seguirán siendo la fuente principal
                de nutrición de tu bebé.</b>
            </p>
            <br/>
            <p>
                Con baby led weaning o auto alimentación, si tu bebé ya cumple con todos 
                <%= link_to "los requisitos", pages_edad_path%> y están listos para comenzar, al principio será una vez al 
                día o cada dos días. Recuerda que al principio tu bebé llevará muy poco o 
                <%= link_to "tal vez nada a la boca", pages_cantidades_path%>. Será más bien una actividad lúdica en la que 
                practica su coordinación óculo-manual y motricidad gruesa (llevar comida 
                con sus manos a la boca) y se familiarizará con diferentes texturas, 
                colores, olores y eventualmente sabores, <%= link_to "entre otros beneficios", pages_beneficios_path%>.
            </p>
            <br/>
            <p>
                Y este es uno de los <%= link_to "principales objetivos de la introducción de sólidos", pages_consejos_para_todos_path%> 
                el primer año: <%#= link_to "introducir a bebé a nuevas texturas y sabores mientras", pages_consejos_para_todos_path(:anchor => "nuevastexturas") -%> 
                que aprende a masticar y deglutir. Si tu bebé sigue en su curva de peso* 
                y se está desarrollando normalmente, entonces está comiendo lo suficiente. 
                Baby led weaning o auto alimentación 
                confía en que tu bebé sabe cuando tiene hambre y cuando ha comido suficiente.
            </p>
            <br/>
            <p>
                A los bebés que se les permite alimentarse ellos mismo, parecen aceptar 
                una gran variedad de comidas. Esto es probablemente porque se concentran 
                no solamente en el sabor sino en la experiencia total; explorar la textura, 
                el color, tamaño y forma. Adicionalmente, con BLW los introducimos a especias, dándoles alimentos que saben 
                rico y no los típicos alimentos sosos sin sabor. ¿A ti te gusta la comida 
                desabrida? ¡A los bebés tampoco! Además al permitirles dejar lo
                que no quieran y tomar lo que sí, los alientas a probar cosas nuevas 
                y tener una experiencia positiva con la comida y la hora de comer.
            </p>
            <br/>
            <p>
                Dicho eso, el hierro es un aspecto muy importante para el desarrollo de 
                tu bebé y por eso se recomienda privilegiar <%= link_to "alimentos altos en hierro", pages_hierro_path%>. 
                Es recomendable dar al menos un alimento alto en hierro diariamente, sin importar de 
                qué manera se introduzca los sólidos (purés o BLW).
            </p>
            <br/>
            <p>
                Los principios generales de nutrición para niños aplican para los bebés 
                que administran su introducción a sólidos. Comida ‘rapida’ (McDonalds, 
                Dominos, Burger King) o preparada no son adecuadas por su alto contenido 
                de grasas y sobre todo sal. No le des azúcar y evita saborizantes 
                artificiales. Básicamente dale a tu bebé la comida que preparas tú, 
                evita agregarle sal y en su lugar utiliza especias para darles sazón. 
                Esto es un hábito excelente que podrás incorporar y continuar en tu vida
                díaria.
            </p>
            <br/>
            <p>
                *Ojo: si tu bebé ha sido amamantado exclusivamente desde que nació, 
                su peso podría ser menor que los bebe de fórmula ya que la leche materna 
                se ajusta al requerimiento calórico de tu bebé y la fórmula es estática, 
                por lo que algunos días aporta calorías de mas y esto puede resultar en 
                bebés de mayor peso. Lo que importa es que tu bebé siga en su curva. 
                Dicho de otra manera, si tu bebé siempre ha estado en el percentil 50, 
                que siga en el percentil 50.
            </p>
        </div>
    </div>
</div>

app/views/pages/primeros_auxilios.html.erb
<div class="container">
    <div style="background:transparent !important" class="jumbotron vertical-center">
        <div class="container content">
            <h1 class="entry-title">Primeros Auxilios</h1>
            <p>
                <b class="onceUpon">Los cursos de primeros auxilios </b>son <u>siempre</u> una buena idea, son la diferencia entre la vida y la muerte. Es por eso que es recomendable tomar un curso en cualquier etapa de tu vida. Y más aún cuando eres, o serás,
                mama o papa. Sobre todo cursos de primeros auxilios para bebés y niños menores. Siempre es importante estar preparado para cualquier emergencia.
            </p>
            <br/>
            <p>
                Si no has tomado un curso, siempre es un buen momento. De esta manera estarás preparado para cualquier eventualidad. Recuerda que un bebé o niño pequeño se puede ahogar con cualquier objeto que se meta a la boca y el ahogamiento nos sucede también a los
                adultos entonces sin importar de qué manera vayas a introducir sólidos, un curso de primeros auxilios es esencial.
            </p>
        </div>
    </div>
</div>